baseURL                   = "https://example.com"
builddrafts                = false
languageCode               = "en"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 8

theme                      = "AllinOne"
title                      = "Curt Poff"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year/:month/:day/:slug/"


[taxonomies]
  tag                      = "tags"
  #series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "https://blog.curtpoff.com"

  [[menu.main]]
    name                   = "Contact"
    weight                 = -110
    identifier             = "contact"
    url                    = "contact/"

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"



[params]
  faviconfile              = "img/zheng.png"               # from static/
  avatar                   = "/img/androidify300.png"             # path to image in static dir e.g img/avatar.png
  author                   = "Curt Poff"
  description              = ["Tucson resident, Missouri native, web guy, sports fan."]           # appears in the site header when set to a non-empty string
  #welcome_head             = "Hello, World!"
  #welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'year'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "curt.poff@gmail.com"
  github                   = "//github.com/cpoff"
  linkedin                 = "//linkedin.com/in/cpoff"
  facebook                 = "//facebook.com/fatback"
  #googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/cpoff"
  #px500                    = "//px500"
  instagram                = "//instagram.com/cpoff"
  telegram                = "//t.me/cpoff"
  keybase                = "//keybase.io/cpoff"
  include_rss              = true  

  # analytics
#  googleAnalytics          = "your-google-analytic-id"
