title = "Curt Poff"
baseURL = "/"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
#googleAnalytics = ""
#disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Osprey Example Site"
  author = "Curt Poff"
  description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
  logoBig = "/img/androidify300.png"
#  logoSmall = "/osprey-logo.png"
  favicon = "favicon.png"
  opengraphImage = "/img/androidify300.png"
  email = "curt.poff@gmail.com"
  googleTagManger = ""
  customCSS = false

  # Social media links in footer
  twitter = "cpoff"
  linkedin = "cpoff"
  github = "cpoff"
#  facebook = "fatback"
  instagram = "cpoff"

  # Copyright and theme author credit in footer
  copyright = true
  credit = true

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
#  ajaxFormspree = false
#  ajaxFormspreeGold = false
#  ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 10
[[menu.main]]
  name = "Work"
  url  = "/#work"
  weight = 20
[[menu.main]]
  name = "Blog"
  url  = "/posts"
  weight = 30
[[menu.main]]
  name = "Contact"
  url  = "/contact"
  weight = 40
