baseurl = "http://www.example.com"
title = "Curt Poff"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"
#paginate = 10
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Curt Poff"
    description = "Curt Poff is a veteran techie now living in Tucson. Past homes include Portland and the Bay Area, where he worked for Macworld, Walmart.com, and Nike."
    keywords = "blog, developer, personal, Tucson, Arizona, Portland, Oregon, Portland State, Timbers, Chiefs, Royals, Mizzou, producer, project manager,"
    info = "Tucson resident, Missouri native"
    avatarurl = "img/androidify300.png"
		faviconfile = "img/favicon.ico"               # from static/
    #footercontent = "Enter a text here."
    dateformat = "January 2, 2006"
    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
#    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 15
    url = "https://github.com/cpoff/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 10
    url = "https://twitter.com/cpoff/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 30
    url = "https://www.linkedin.com/in/cpoff/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 20
    url = "https://instagram.com/cpoff"
[[params.social]]
		name = "Facebook"
		icon = "fab fa-facebook"
		weight = 40
		url = "https://facebook.com/fatback"
[[params.social]]
		name = "Keybase"
		icon = "fab fa-keybase"
		weight = 70
		url = "https://keybase.io/cpoff"
[[params.social]]
		name = "Telegram"
		icon = "fab fa-telegram"
		weight = 100
		url = "https://t.me/cpoff"



[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 2
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 1
        url = "https://blog.curtpoff.com"

        [[languages.en.menu.main]]
        name = "Resume"
        weight = 3
        url = "/resume/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 5
        url = "/contact/"
